name: continuous integration
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Fix worktree ownership
        uses: docker://nixos/nix:2.24.2
        with:
          args: chown root ./ -R
      - name: Run gradle
        uses: docker://nixos/nix:2.24.2
        with:
          args: nix develop --command gradle build javadoc
        env:
          NIX_CONFIG: extra-experimental-features = flakes nix-command
